apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: acme-corp
  description: A collection of all Backstage example Groups
  tags:
    - java
    - data
spec:
  type: service
  lifecycle: experimental
  owner: team-a
#   system: artist-engagement-portal
